[package]
name = "pi_rust"
version = "0.1.0"
edition = "2021"
authors = ["Arpad Palinkas <arpad.palinkas@gmail.com>"]
description = "Pi Network SDK Rust implementation"
license = "PiOs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stellar_sdk = { git = "https://github.com/palinko91/stellar-sdk.git", branch = "master" }
stellar-base = "0.5.0"
sodiumoxide = "=0.2.6"
serde = "1.0.183"
serde_json = "1.0.105"
reqwest = { version = "0.11.18", features = ["json"] }
tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1.0.75"

[dev-dependencies]
dotenvy = "0.15.7"
tokio  = { version = "1.32.0", features = ["full"] }